[package]
name = "mkdesktop"
version = "0.1.0"
authors = ["Nigel Baillie <metreckk@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.27.0"
path_abs = "~0.4"
dirs = "1.0.5"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

